### ISSUE TITLE
Add attributes from Geojson to SVG

### ISSUE THREAD

**Issue by Mohsen62m** [derhuerst/geojson-to-svg-cli#5]
Hello,

Can we add some attributes from Geojson to SVG, with providing which properties or geometries in Geojson we need to add in SVG, with "geojson-to-svg-cli"?

**Comment by derhuerst** [comment]
What attributes do you have in mind? Custom user-defined attributes, exposed as [`data-*` SVG attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/data-*)?

**Comment by derhuerst** [comment]
`geojson-svgify`, the library beneath `geojson-to-svg-cli`, [already has an option `computeProps(feature)`](https://github.com/juliuste/geojson-svgify/blob/da16a4ed76d87322f8fb99599602fc347da67e52/readme.md#api) which can be used for this. **PR welcome!**

**Comment by Mohsen62m** [comment]
I need "code" and "city" and "type" in geojson file to be added in my svg.
"properties": { "code": "1111", "city": "cityname" }
"geometry": { "type": "Polygon", "coordinates":  ... }

 I have very geojson files to convert them to svg.

**Comment by Mohsen62m** [comment]
I can not see `computeProps(feature)` in "Guide" section. 
And `feature` is equvalent to `polylines?`
Is there an example of using `geojson-svgify`?

**Comment by derhuerst** [comment]
[The readme of `geojson-svgify` only briefly mentions `computeProps`.](https://github.com/juliuste/geojson-svgify/blob/da16a4ed76d87322f8fb99599602fc347da67e52/readme.md#api) It calls `computeProps` for every feature returned by [`geojson-flatten`](https://www.npmjs.com/package/geojson-flatten).

We would have to introduce a command line option that in turn uses `computeProps` to add attributes to the SVG elements.

**Comment by Mohsen62m** [comment]
OK. Thank you a lot.

**Comment by derhuerst** [comment]
Please submit a PR if you happen to implement the changes.

**Comment by derhuerst** [comment]
Published as `geojson-to-svg-cli@1.0.0`.
